[pytest]
testpaths = src/tests
pythonpath = src
addopts = -v --html=reports/report.html --self-contained-html --alluredir=allure-results
markers =
    smoke: Smoke tests
    regression: Regression tests
    image_validation: Image validation tests
    e2e: End-to-end flow tests
    bdd: BDD scenarios
